### ISSUE TITLE
AcmeClient.AuthorizeIdentifier(string) throws NullReferenceException

### ISSUE THREAD

**Issue by peske** [ebekker/ACMESharp#236]
Hi guyz

First to tell that I'm new in this, but kind of experienced in C#...

I've ran into an issue with calling AcmeClient.AuthorizeIdentifier method - it throws NullReferenceException. I've checked that the client is initialized. And I'm sending a valid domain name as a parameter.

Am I doing something wrong?

Thanks!

**UPDATE:** I've forgot to mention that I'm using version v0.8.1.214-EA.

Here's the stack trace:
```
   at ACMESharp.JOSE.RS256Signer.ExportJwk(Boolean canonical)
   at ACMESharp.AcmeClient.ComputeAcmeSigned(Object message, ISigner signer)
   at ACMESharp.AcmeClient.RequestHttpPost(Uri uri, Object message)
   at ACMESharp.AcmeClient.AuthorizeIdentifier(String dnsIdentifier)
   at MicroNet.LetsEncrypt.LetsEncryptWrapper.Authorize(String host) in C:\ITGit\Temp\MicroNet\LetsEncrypt\MicroNet.LetsEncrypt.Lib\LetsEncryptWrapper.cs:line 379
   at MicroNet.LetsEncrypt.LetsEncryptWrapper.GetCertificate(String host) in C:\ITGit\Temp\MicroNet\LetsEncrypt\MicroNet.LetsEncrypt.Lib\LetsEncryptWrapper.cs:line 125
   at MicroNet.LetsEncrypt.Program.Main(String[] args) in C:\ITGit\Temp\MicroNet\LetsEncrypt\MicroNet.LetsEncrypt.Cli\Program.cs:line 11
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by peske** [comment]
**STUPID ME!!!**

I've disposed RS256Signer used for creating the agent... It's OK now.

Sorry guyz, and thanks!
