### ISSUE TITLE
Runtime Issue? Could not load file or assembly 'Microsoft.SharePoint.Client.ServerRuntime'

### ISSUE THREAD

**Issue by bitsfarm** [ebekker/ACMESharp#262]
Any ideas on this?  It seems to get injected at runtime under when included in Web Services based app SolidCP,  I have verified the code in a console app so appears to be an environment issue.

`
System.Web.Services.Protocols.SoapException: System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.SharePoint.Client.ServerRuntime, Version=14.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its dependencies. The system cannot find the file specified.
  at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
  at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
  at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
  at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
  at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
  at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
  at Microsoft.Internal.AttributeServices.GetAttributes[T](ICustomAttributeProvider attributeProvider)
  at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
  at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(ImportDefinition definition)
  at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
  at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
  at System.ComponentModel.Composition.Hosting.AggregateCatalog.GetExports(ImportDefinition definition)
  at System.ComponentModel.Composition.Hosting.AggregateCatalog.GetExports(ImportDefinition definition)
  at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
  at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
  at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
  at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
  at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
  at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
  at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
  at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
  at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
  at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
  at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
  at System.ComponentModel.Composition.Hosting.ImportEngine.TryGetExports(ExportProvider provider, ComposablePart part, ImportDefinition definition, AtomicComposition atomicComposition)
  at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition)
  at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportsStateMachine(PartManager partManager, ComposablePart part)
  at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports)
  at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImports(ComposablePart part)
  at System.ComponentModel.Composition.Hosting.CompositionServices.TryInvoke(Action action)
  at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
  at ACMESharp.Ext.ExtCommon.InitExtConfig[TExtConfig]() in C:\DATA\Production\SolidCPv2\ACMESharp\ACMESharp\ACMESharp\Ext\ExtCommon.cs:line 126
  at ACMESharp.Ext.ExtCommon.ReloadExtConfig[TExtConfig](TExtConfig existing) in C:\DATA\Production\SolidCPv2\ACMESharp\ACMESharp\ACMESharp\Ext\ExtCommon.cs:line 67
  at ACMESharp.ACME.ChallengeDecoderExtManager.Reload() in C:\DATA\Production\SolidCPv2\ACMESharp\ACMESharp\ACMESharp\ACME\ChallengeDecoderExtManager.cs:line 44
  at ACMESharp.ACME.ChallengeDecoderExtManager.AssertInit() in C:\DATA\Production\SolidCPv2\ACMESharp\ACMESharp\ACMESharp\ACME\ChallengeDecoderExtManager.cs:line 55
  at ACMESharp.ACME.ChallengeDecoderExtManager.GetProvider(String type, IReadOnlyDictionary`2 reservedLeaveNull) in C:\DATA\Production\SolidCPv2\ACMESharp\ACMESharp\ACMESharp\ACME\ChallengeDecoderExtManager.cs:line 34
  at ACMESharp.AcmeClient.DecodeChallenge(AuthorizationState authzState, String challengeType) in C:\DATA\Production\SolidCPv2\ACMESharp\ACMESharp\ACMESharp\AcmeClient.cs:line 424
`

**Comment by WallyRanson** [comment]
It says its the file "Microsoft.SharePoint.Client.ServerRuntime, Version=14.0.0.0" that is missing.
I am not sure that is part of ACMESharp. Sounds more like something with Sharepoint or IIS.

**Comment by bitsfarm** [comment]
Hi,  The error is only raised when the code is executed as part of SolidCP.Server, an open source hosting control panel application.  The same code executed within a standalone console app runs without problem, so it seems to me that AcmeSharp is detecting something from the bin when the Decode methods are being executed.

**Comment by WallyRanson** [comment]
Its more likely that the SolidCP.Server setup an enviroment for all its PowerShells scripts by loading a set of modules and here the Sharepoint module is part of that list.

If you look at the error, then you can see that the error is caused by a call from an ACMESharp module, but the error actually occurs in System.ModuleHandle.ResolveType.
I see this as more of an indication that a module loading has failed earlier.

**Comment by ebekker** [comment]
I think you need to talk to the SolidCP folks.
