### ISSUE TITLE
Unable Use Import-Module ACMESharp

### ISSUE THREAD

**Issue by CarlGalloy** [ebekker/ACMESharp#265]
Hi,
I have a problem on first [Quick Start](https://github.com/ebekker/ACMESharp/wiki/Quick-Start) Steps, Importing Module
I read Requirement section on wiki. I have .Net4.5 WMF 4 that included Power Shell 4 but now we get below error when use command: Import-Module ACMESharp

``` Import-Module : Could not load file or assembly
'file:///C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ACMESharp\ACMESharp.POSH.dll' or one of its dependencies.
Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
```
My PowerShell Information by run this cmdlet : `$PSVersionTable`

Name                   |                    Value
------------------ | ------------------
PSVersion                 |                 4.0
WSManStackVersion       |           3.0
SerializationVersion         |           1.1.0.1
CLRVersion              |                  4.0.30319.18408
BuildVersion              |                6.3.9600.16406
PSCompatibleVersions      |        {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion  |    2.2

Windows Information:

- Microsoft Windows 7 Ultimate
- Service Pack 1
- **OS Version:** 6.1.7601 Service Pack 1 Build 7601
- 32-bit System
- Use Windows Management Framework  4 (WMF 4.0)
- I Use Manual Installation & therefor Extract _[ACME-posh.zip](https://github.com/ebekker/ACMESharp/releases/download/v0.8.1.0-EA/ACME-posh.zip)_ to `Module` Directory

And screenshot of my PowerShell Windows.
![pss](https://user-images.githubusercontent.com/30363721/28507846-2a6cce82-704b-11e7-9e75-8d092f2cc130.png)

Thanks.

**Comment by WallyRanson** [comment]
Maybe its your .NET core that needs to be updated or installed.
https://www.microsoft.com/net/download/core

**Comment by CarlGalloy** [comment]
@WallyRanson  Thanks, 
My .Net Version is 4.5.1 
Is really need update?If Yes. To What Version?

Screen Shot of my .Net's that install on my system.
![mydotnet](https://user-images.githubusercontent.com/30363721/28554759-92d084f8-7110-11e7-8119-51327334768e.png)

**Comment by WallyRanson** [comment]
I have tried to see what could cause it, but I could not find anything obvious, so one with more experience in the inner workings of this module have to take it from here.

Only thing I noticed is that my CLRVersion in $PSVersionTable is 4.0.30319.42000, but that is on Windows 10.
I do not know if you can reach the same version, but if you have not done it yet, then see if there are any Windows Updates available. When you install the .NET framework then its not the updated version. Updates then come later through Windows Update.

**Comment by ebekker** [comment]
When you get the error, you should see if the exception can provide more details.  Try the following:

```powershell
$lastError = $Error[0]
$lastEx = $lastError.Exception
while ($lastEx) {
    echo "Exception:  $lastEx"
    $lastEx = $lastEx.InnerException
}
```

**Comment by CarlGalloy** [comment]
@ebekker 
I'm not too familiar with Shell Coding.
Is the above code must run just on command of PowerShell ISE?

**Comment by ebekker** [comment]
Yes, you can just paste it into your ISE terminal (the blue window) after you encounter the error and hit enter.

**Comment by CarlGalloy** [comment]
Result:(_Copy all Powershell ISE terminal text,include  `Import-Module ACEMSharp` and `$PSVersionTable` Command and your code_)

````javascript
PS C:\Users\Administrator> $PSVersionTable

Name                           Value                                                                                 
----                           -----                                                                                 
PSVersion                      5.0.10586.117                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                               
BuildVersion                   10.0.10586.117                                                                        
CLRVersion                     4.0.30319.18408                                                                       
WSManStackVersion              3.0                                                                                   
PSRemotingProtocolVersion      2.3                                                                                   
SerializationVersion           1.1.0.1                                                                               



PS C:\Users\Administrator> Import-Module ACMESharp
Import-Module : Could not load file or assembly 
'file:///C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ACMESharp\ACMESharp.POSH.dll' or one of its dependencies. Operation is 
not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module ACMESharp
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
 

PS C:\Users\Administrator> $lastError = $Error[0]
$lastEx = $lastError.Exception
while ($lastEx) {
    echo "Exception:  $lastEx"
    $lastEx = $lastEx.InnerException
}
Exception:  System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Windows\system32\WindowsPowerShell\v1.0\Modules\A
CMESharp\ACMESharp.POSH.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ACMESharp\ACMESharp.POSH.dll' ---> System.NotSupportedException
: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous ver
sions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. 
If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwli
nk/?LinkId=155569 for more information.
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleN
ame, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlag
s manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found, String shortModuleName, Boolean disa
bleFormatUpdates)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(Boolean trySnapInName, String moduleName, String fileName, Assem
bly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, 
String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String 
prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& f
ound, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo parentModule, ModuleSpecification moduleSp
ecification, String moduleBase, Boolean searchModulePath, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcess
ingFlags manifestProcessingFlags, Boolean loadTypesFiles, Boolean loadFormatFiles, Object privateData, Boolean& found, String shortMod
uleName)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo scriptInfo, Hash
table data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, 
Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(ExternalScriptInfo scriptInfo, ManifestProcessingFlags manifes
tProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModule
Options& options)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String 
prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& f
ound, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(PSModuleInfo parentModule, String moduleName, String fileBase
Name, String extension, String moduleBase, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manife
stProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(PSModuleInfo parentModule, Boolean found, IEnumerable`1 modul
ePath, String name, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, PSModuleInfo& modul
e)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(Boolean found, IEnumerable`1 modulePath, String name, Session
State ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, PSModuleInfo& module)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String na
me)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()


Exception:  System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the 
assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by 
default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources 
switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

PS C:\Users\Administrator>````

**Comment by CarlGalloy** [comment]
Yes.Yes..Problem Solved.I right click on file `ACMESharp.POSH.dll` and click `unblock` button below of `Advance`  button on file properties dialog.

**Comment by srp140830** [comment]
Hello All,
I am facing this issue.  All my files are unblocked. 
Has Anyone has found a correct solution to this issue.

Thanks
Sanket
